Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Products-dev"
      AttributeDefinitions:
        - AttributeName: "ProductId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ProductId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
