version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - ls
      - echo "Installing dependencies..."
      - npm install -g serverless
      - npm install
  build:
    commands:
      - echo "Packaging the Serverless service..."
      - serverless package
  post_build:
    commands:
      - echo "Deploying the Serverless service..."
      = serverless package
      - serverless deploy

artifacts:
  files:
    - '**/*'
