service: ecommerce-microservice

provider:
  name: aws
  runtime: nodejs18.x # Updated to a valid Node.js runtime
  region: us-east-1

functions:
  # Lambda functions for managing products
  createProduct:
    handler: src/lambda/createProduct.handler
    events:
      - http:
          path: product
          method: post

  getProduct:
    handler: src/lambda/getProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: get

  updateProduct:
    handler: src/lambda/updateProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: put

  deleteProduct:
    handler: src/lambda/deleteProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: delete

  # Lambda functions for managing taxonomy
  createTaxonomy:
    handler: src/lambda/createTaxonomy.handler
    events:
      - http:
          path: taxonomy
          method: post

  getTaxonomy:
    handler: src/lambda/getTaxonomy.handler
    events:
      - http:
          path: taxonomy/{ProductId}
          method: get

resources:
  Resources:
    # DynamoDB Table for Products (with stage suffix)
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products-${opt:stage, 'dev'}  # Use the stage name (e.g., dev, prod)
        AttributeDefinitions:
          - AttributeName: ProductId
            AttributeType: S
        KeySchema:
          - AttributeName: ProductId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # DynamoDB Table for Taxonomy (use the stage-based naming convention)
    TaxonomyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Taxonomy-${opt:stage, 'dev'}  # Use the stage name (e.g., dev, prod)
        AttributeDefinitions:
          - AttributeName: TaxonomyId
            AttributeType: S
        KeySchema:
          - AttributeName: TaxonomyId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
