service: ecom-product-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  # Lambda functions for managing products
  create-product:
    handler: src/lambda/createProduct.handler
    events:
      - http:
          path: product
          method: post

  get-product:
    handler: src/lambda/getProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: get

  update-product:
    handler: src/lambda/updateProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: put

  delete-product:
    handler: src/lambda/deleteProduct.handler
    events:
      - http:
          path: product/{ProductId}
          method: delete

  # Lambda functions for managing taxonomy
  create-taxonomy:
    handler: src/lambda/createTaxonomy.handler
    events:
      - http:
          path: taxonomy
          method: post

  get-taxonomy:
    handler: src/lambda/getTaxonomy.handler
    events:
      - http:
          path: taxonomy/{ProductId}
          method: get

resources:
  Resources:
    # DynamoDB Table for Products
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: ProductId
            AttributeType: S
        KeySchema:
          - AttributeName: ProductId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # DynamoDB Table for Taxonomy
    TaxonomyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Taxonomy-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: TaxonomyId
            AttributeType: S
        KeySchema:
          - AttributeName: TaxonomyId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # AppSync API
    AppSyncApi:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        Name: EcommerceGraphQLApi-${opt:stage, 'dev'}
        AuthenticationType: API_KEY

    # AppSync Schema
    AppSyncSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        DefinitionS3Location: src/graphql/schema.graphql

    # AppSync API Key
    AppSyncApiKey:
      Type: AWS::AppSync::ApiKey
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        Expires: 1672531199  # Replace with a valid timestamp for API key expiry
